### ISSUE TITLE
Problem of `train_net()` in REINFORCE algorithm.

### ISSUE THREAD

**Issue by fuyw** [seungeunrho/minimalRL#26]
Thanks for the high quality implementations. But I have a question about `train_net()` in REINFORCE algorithm:

```python
    def train_net(self):
        R = 0
        for r, prob in self.data[::-1]:
            R = r + gamma * R
            loss = -torch.log(prob) * R
            self.optimizer.zero_grad()
            loss.backward()
            self.optimizer.step()
        self.data = []
```
The policy is updated for each step of an episode. But the policy is supposed to be updated after a complete episode (or batch of episodes).

Since after we do an update, the policy is changed, and the data collected is no longer useful according to the theory.

**Comment by seolhokim** [comment]
That's right. policy has to be updated after for loop and i fixed it. you can find the changed code under this issue.

**Comment by fuyw** [comment]
Thanks for your reply.

**Comment by fuyw** [comment]
I find an interesting problem that: the policy converges slower after we fix the bug (compared in wall time).

Is this problem too easy that the policy can converge faster even it is updated per step? I don't know a reasonable explanation for this (or may it is just a coincidence). Could you please give me some hints?

Thank you very much.

**Comment by seolhokim** [comment]
I didn't think about that. I fixed slow converge problem. 
But, master branch correctly implemented the REINFORCE pseudo code.
So, my code might be wrong. I don't know why it can be updated like that.
Don't trust my code so much. haha. 
I will ask that for some other people soon and I will tell you.
Anyway, I give up my exam next week for you. haha 
It took longer than I thought to fix and find reason why master branch's update is reasonable.
If I have a time, then I will help you anytime.
Thanks.

**Comment by fuyw** [comment]
Thanks for your help. Really sorry for disturbing your exam. 
Good luck and hope you can do well in the exam.
Many thanks.
