### ISSUE TITLE
Termination of a CartPole episode in REINFORCE.py

### ISSUE THREAD

**Issue by aliansari2** [seungeunrho/minimalRL#28]
Hi.
I think REINFORCE.py:44 should be placed after REINFORCE.py:46. Because once a single episode is terminated, the value of "done" will be False (and won't be reset), causing the main function to skip the while loop in the subsequent episodes.
After all, I'm not sure about this issue. I'm a total newbie.
BTW, all of the implementations are highly efficient, easy-to-customize, easy-to-understand, and very helpful. Thank you for sharing.

**Comment by seungeunrho** [comment]
Fixed!!! Sorry!!!! and thankyou!!!
