### ISSUE TITLE
Questions about A3C

### ISSUE THREAD

**Issue by LoveRL** [seungeunrho/minimalRL#29]
Hi, 
Thanks for your simple and awesome A3C code.

I got some of the questions to ask.

**Q.** Why did you put the 'test' process into multi-process with other actor-learner thread?
I think that the 'test' process should be called after all of the other actor-learner threads are done.
OR Is it just to check a train performance of global_model (=test)?

Thank you.

**Comment by seungeunrho** [comment]
As you said, it is just for checking the performance during training! 
Thanx
