### ISSUE TITLE
Missing done mask?

### ISSUE THREAD

**Issue by Junyoungpark** [seungeunrho/minimalRL#32]
혹시 critic target에서 `done mask`를 곱해주는것을 빼먹으신거 아닌가요?

https://github.com/seungeunrho/minimalRL/blob/7095e0f9ffa408959842528714ba687743661c14/ddpg.py#L89

**Comment by seolhokim** [comment]
#21

**Comment by seungeunrho** [comment]
준영님 안녕하세요, 잘 지내시죠!?
감사합니다 다소늦었지만.. 처리하였습니다!!

**Comment by Junyoungpark** [comment]
ㅎㅎ 잘지내고 있습니다! 승은님께선 잘 지내고 계신지요!
즐거운 연말 보내시길 바라겠습니다.
박준영 드림

2020년 11월 11일 (수) 오후 3:16, seungeunrho <notifications@github.com>님이 작성:
