### ISSUE TITLE
RuntimeError while running DDPG.py

### ISSUE THREAD

**Issue by rl-max** [seungeunrho/minimalRL#34]
Hi, I got RuntimeError when I executed DDPG.py.
It seems to be occurred during training process of QNet.

**RuntimeError: Expected object of scalar type Float but got scalar type Double for argument #2 'mat1' in call to _th_addmm**

I'm using torch 1.5.0 and Python 3.7.3
Is there anyone with the same problem as me?

**Comment by seolhokim** [comment]
fixed

**Comment by rl-max** [comment]
thank you so much!!
