### ISSUE TITLE
Maybe a bug in SAC Implementation?

### ISSUE THREAD

**Issue by arthur-x** [seungeunrho/minimalRL#40]
https://github.com/seungeunrho/minimalRL/blob/a88447c0f15f63630316de7bbd0b3155fb821dac/sac.py#L73

The actions are w.r.t. s_prime, however, the Q-values are evaluated for s. 

https://github.com/seungeunrho/minimalRL/blob/a88447c0f15f63630316de7bbd0b3155fb821dac/sac.py#L76

This doesn't match. Is this a bug?

**Comment by seungeunrho** [comment]
Oh my,  you are definitely right.
Thanks, I updated the code.
