### ISSUE TITLE
Add minimal IMPALA？

### ISSUE THREAD

**Issue by meadewaking** [seungeunrho/minimalRL#51]
Hello,

its a fantastic job and really helpful for me! Is it possible to add IMPALA by revamp A3C？
IMPALA is more efficient than A2C and A3C，all the code I find in github for that is detailed and complicated

**Comment by seungeunrho** [comment]
Sorry for laaaaate response.
Just added `vtrace.py`  which is a core update algorithm in IMPALA.
If you want to use IMPALA, just add some asynchronous executions to it.

**Comment by meadewaking** [comment]
thank you！！！！
that's help me a lot
